version: "3.7"
services:
  mysql:
    image: "mysql:5.7"
    container_name: "db-query-mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
      MYSQL_HOST: "localhost"
